config/routes.rb
Rails.application.routes.draw do
  get '/hobbies' => 'pages#hobbies'
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
    
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      
      ContactMailer.contact_email(name, email, body).deliver
      
      flash[:success] = "Message has been sent!"
      redirect_to new_contact_path
    else
      flash[:danger] = "Error occured. Please fill out all fields and submit again."
      redirect_to new_contact_path
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        render :layout => 'home_view'
    end
    
    def about
    end
    
    def hobbies
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
</head>
<body>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h2 id="contact-h2">Thank you for visiting my site!</h2>
    <h4 id="contact-h">If you would like to contact me, please fill out the form below!</h4>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
  <link rel="shortcut icon" href="http://i1194.photobucket.com/albums/aa366/jtv_24/bed3f0ea-8bdc-44ba-8054-e6d88ea6fca8_zps60okttto.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,600' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <div class="head-text">
          <div class="head-logo">
            <img src="http://i1194.photobucket.com/albums/aa366/jtv_24/bed3f0ea-8bdc-44ba-8054-e6d88ea6fca8_zps60okttto.png", alt="JV">
          </div>
          <div class="site-name">
            <strong>Joseph</strong>Verrastro
          </div>
        </div>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contacts/new">Contact</a></li> 
        <li>
          <a href="https://www.linkedin.com/in/josephverrastro", class: 'navbar-brand', target="_blank">
            <i class="fa fa-linkedin"></i> LinkedIn
          </a>
        </li> 
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>
</div>

<footer>
  <div class="container text-center ">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to about_path do %>About<%end%></li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to new_contact_path do %>Contact<%end%></li>
          </ul>
          </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="https://www.linkedin.com/in/josephverrastro" target="_blank">LinkedIn</a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="/">Joseph Verrastro</a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>
</body>
</html>

app/views/layouts/home_view.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
  <link rel="shortcut icon" href="http://i1194.photobucket.com/albums/aa366/jtv_24/bed3f0ea-8bdc-44ba-8054-e6d88ea6fca8_zps60okttto.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,600' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <div class="head-text">
          <div class="head-logo">
            <img src="http://i1194.photobucket.com/albums/aa366/jtv_24/bed3f0ea-8bdc-44ba-8054-e6d88ea6fca8_zps60okttto.png", alt="JV">
          </div>
          <div class="site-name">
            <strong>Joseph</strong>Verrastro
          </div>
        </div>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li id="nav-color"><a href="/">Home</a></li>
        <li id="nav-color"><a href="/about">About</a></li>
        <li id="nav-color"><a href="/contacts/new">Contact</a></li> 
        <li id="nav-color">
          <a href="https://www.linkedin.com/in/josephverrastro", class: 'navbar-brand', target="_blank">
            <i class="fa fa-linkedin"></i> LinkedIn
          </a>
        </li> 
      </ul>
    </div>
  </div>
</nav>

<header id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
      <div class="item active">
        <%= link_to about_path do %>
          <div class="fill" style="background-image:url('http://goo.gl/STBEQz');" alt="my pic"></div>
          <div class="carousel-caption">
              <h2 id="caption-h2">WELCOME TO MY SITE!</h2>
          </div>
        <% end %>
      </div>
      <div class="item">
        <%= link_to hobbies_path do %>
          <div class="fill" style="background-image:url('http://goo.gl/oEeizQ');" alt="cricket"></div>
          <div class="carousel-caption">
              <h2 id="caption-h2">Check out my Hobbies, Interests and LinkedIn Profile!</h2>
          </div>
        <% end %>
      </div>
      <div class="item">
        <%= link_to new_contact_path do %>
          <div class="fill" style="background-image:url('http://goo.gl/DWVOfc');" alt="leaves"></div>
          <div class="carousel-caption">
              <h2 id="caption-h2">Contact me if you're interested!</h2>
          </div>
        <% end %>
      </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="icon-next"></span>
  </a>
  
  <div class="learn-more">
		<div class="container">
		  <div class="row text-center col-md-12">
		    <h3 id="me">ME, AT A GLANCE!</h3>
		    <h4 id="me-info">Hover over the logos for more information</h4>
		    <br>
		  </div>
			<div class="col-md-4">
				<div id="icons" class="text-center">
					<i id="font-logo" class="fa fa-desktop"></i>
					<p class="description"><br><br>I love working with computers and other technology! From my humble beginnings of learning how to type on a keyboard, to 
          setting up routers and networks, to my newly found love to writing web dev code, computers and all it intails has been in my blood!</p>
				</div>
			</div>

			<div class="col-md-4">
				<div id="icons" class="text-center">
					<i id="font-logo" class="fa fa-futbol-o"></i>
					<p class="description"><br><br>Throughout my life I always had an interest in sports. I played baseball, basketball and football and was lucky enough to be 
          a part of two baseball state championship teams! But sports in general are in my DNA! I love to compete!</p>
				</div>
			</div>

			<div class="col-md-4">
				<div id="icons" class="text-center">
					<i id="font-logo" class="fa fa-camera"></i>
					<p class="description">In recent years I've taken an interest in photography and using Adobe Photoshop for my pictures! I love to put a little artistic spin on even a normal photo! 
            Through that time I used photoshop to touch up all of my photos. Photoshopping my photos allows my creative juices to flow, and I
            like to utilize that abilty with my web design and development! Take a look at some of my work <a id="here" href="/hobbies">HERE!</a></p>
				</div>
			</div>
		</div>
	</div>
	
  
  <script>
  $('.carousel').carousel({
      interval: 7000
  });
  
  $(document).ready(function() {
    $('.item').mouseenter(function() {
      $('.carousel-caption').fadeTo('slow', 1);
    });
    $('.item').mouseleave(function() {
      $('.carousel-caption').fadeTo('slow', 0);
    });
  });
  </script>
  
<footer>
  <div class="container text-center ">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to about_path do %>About<%end%></li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to new_contact_path do %>Contact<%end%></li>
          </ul>
          </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="https://www.linkedin.com/in/josephverrastro" target="_blank">LinkedIn</a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="/">©Joseph Verrastro</a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>
</header>
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
</head>
<body>
    <div class="well">
        
        <div class="row text-center"><!--row 1-->
            <br>
            <h1 id="about-header">An <span>ENTIRE</span> page just about <span>ME</span>!?!?</h1>
            <br>
            <br>
        </div><!--row 1-->
    
        <ul>
        <div class="row text-center"><!--row 2-->
            <div class="col-md-3">
                <img src="https://goo.gl/SsrGju" class-"img-responsive" alt="My photo" id="profile">
            </div>
            <div class="col-md-9" id="goals-b">
                <h2 id="goals-h2">My Goals and Objective!</h2>
                <p id="about-me-p">My overall <span>objective</span> is to work in an <span>exciting</span> fast-paced environment, 
                offering opportunities for personal and professional growth, through <span>web development</span> opportunities.
                My overall goal as a web developer is to continue to learn and adapt to new changes and experiences. I believe
                that, in order to excel at something as complex as web development, it boils down to two things. <span>First</span>,
                you need to continue to <span>adapt and learn</span>. <span>Secondly</span>, and I believe most importantly, you need to be <span>passionate</span> about
                what you do as a web developer! And I know I will continue to be passionate about development and will strive to learn
                more each and every day!</p>
            </div>
        </div><!--row 2-->
        </ul>
        <ul>
        <div class="row text-center">
            <div class="col-md-3">
                <h3 id="about-h3-a">About Me</h3>
            </div>
        </div>
        </ul>
        
        <ul>
        <div class="row">
            <div class="col-md-3">
                <p id="about-me-p">As you may have guessed it, my name is <span>Joseph Verrastro</span> and I am a new, up-and-coming web developer!
                 I <span>completed</span> the <span>Full-stack Web Developer Bootcamp by Coder Manual</span> on November 17,2015 and received my certificate as a full-stack
                 web developer! During that time I <span>learned</span> many different <span>languages and skills!</span></p>
            </div>
            <div class="col-md-9">
                    <img id="item1" src="http://goo.gl/pE8MZk" class="img-responsive" alt="All languages">
                    <img id="item2" src="http://goo.gl/Vy3JbN" class="img-responsive" alt="What I know">
                    <img id="item3" src="http://www.naugatuckymca.org/wp-content/uploads/2015/12/html5-long-1024x287.png" class="img-responsive" alt="HTML5">
                    <img id="item4" src="http://goo.gl/XKfGx3" class="img-responsive" alt="JavaScript"><!--on-->
                    <img id="item5" src="http://goo.gl/kiAgHV" class="img-responsive" alt="CSS3"><!--on-->
                    <img id="item6" src="http://goo.gl/wAzgNG" class="img-responsive" alt="jQuery"><!--on-->
                    <img id="item7" src="http://goo.gl/eNNtz2" class="img-responsive" alt="Ruby on Rails"><!--on-->
                    <img id="item8" src="http://goo.gl/pE8MZk" class="img-responsive" alt="All languages">
            </div>
        </div>
        </ul>
    </div>
        
        <script>
            var fadeLoop = function($el) {
                $el.fadeOut(2000, function() {
                    var $next = $el.next();
                    if ($next.length == 0) {
                        $next = $el.siblings(":first");
                    }
                    $next.fadeIn(3000, function() {
                        fadeLoop($next);
                    });
                });
            };
            
            $(document).ready(function(){
                $("#item1").siblings().hide();
                fadeLoop($("#item1"));
            });
        </script>
</body>
</html>

app/views/pages/hobbies.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
</head>
<body>

<div class="container">
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">My <span>Photography</span></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/cVCZAl" target="_blank">
            <img class="img-responsive" src="http://goo.gl/XDwVuR" alt="guitar">
        </a>
        <h3>
            <a href="http://goo.gl/cVCZAl" target="_blank">"Light Guitar"</a>
        </h3>
        <p id="photo-p">One of my favorite pictures I have taken! And all it took was a blue glowstick... and a camera!</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/icr2Gt" target="_blank" id="pic-block">
            <img class="img-responsive" src="http://goo.gl/hdNIG1" alt="maternity">
        </a>
        <h3>
            <a href="http://goo.gl/icr2Gt" target="_blank">"Maternity"</a>
        </h3>
        <p id="photo-p">I had the pleasure of shooting maternity photos for my brother and his wife! Since then we've added a new member to our family!</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/GnfxMK" target="_blank">
            <img class="img-responsive" src="http://goo.gl/Os6p6m" alt="chair">
        </a>
        <h3>
            <a href="http://goo.gl/GnfxMK" target="_blank">"Stick in a Chair"</a>
        </h3>
        <p id="photo-p">Another favorite "Light photography" project picture! Stick figure in a chair... he looks relaxed!</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/PK8OZC" target="_blank">
            <img class="img-responsive" src="http://goo.gl/c06APz" alt="rain">
        </a>
        <h3>
            <a href="http://goo.gl/PK8OZC" target="_blank">"Sparkling Rain"</a>
        </h3>
        <p id="photo-p">Who am I kidding? They're all my favorite's! This one in particular was the most phone to shoot with a few sparklers.</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/XOY0nF" target="_blank">
            <img class="img-responsive" src="http://goo.gl/jHP53b" alt="baby shoes">
        </a>
        <h3>
            <a href="http://goo.gl/XOY0nF" target="_blank">"Baby Booties"</a>
        </h3>
        <p id="photo-p">Another piece from my maternity photo shoot! Check out those tiny shoes!</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/FpuHtK" target="_blank">
            <img class="img-responsive" src="http://goo.gl/Hs8p3v" alt="shoes">
        </a>
        <h3>
            <a href="http://goo.gl/FpuHtK" target="_blank">"Glowing Sneaks"</a>
        </h3>
        <p id="photo-p">Woah!! Are those sneakers glowing in the dark!</p>
    </div>
</div>
<div class="row">
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/RpOUCF" target="_blank">
            <img class="img-responsive" src="http://goo.gl/ShdCC4" alt="grasshopper">
        </a>
        <h3>
            <a href="http://goo.gl/RpOUCF" target="_blank">"Grass Friend"</a>
        </h3>
        <p id="photo-p">One of the best macro shots I've taken! Taking this picture was not easy!</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/1bBo1g" target="_blank">
            <img class="img-responsive" src="http://goo.gl/G2v9EX" alt="leaf in road">
        </a>
        <h3>
            <a href="http://goo.gl/1bBo1g" target="_blank">"Shallow Leaf"</a>
        </h3>
        <p id="photo-p">A shallow depth of field shot that makes you wonder if the road ever ends. Note: I wasn't harmed taking this photo!</p>
    </div>
    <div class="col-md-4 portfolio-item">
        <a href="http://goo.gl/tTUFWV" target="_blank">
            <img class="img-responsive" src="http://goo.gl/09OaQE" alt="flower">
        </a>
        <h3>
            <a href="http://goo.gl/tTUFWV" target="_blank">"Fall Flower"</a>
        </h3>
        <p id="photo-p">All shots of nature are great! But this one in particular stands out to me with the depth of field and color!</p>
    </div>
</div>
<hr>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joseph Verrastro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    
</body>

</html>